app:
    resource: '@AppBundle/Controller/'
    type: annotation

card:
    resource: '@CardBundle/Controller/'
    type: annotation

deck:
    resource: '@DeckBundle/Controller/'
    type: annotation

player:
    resource: '@PlayerBundle/Controller/'
    type: annotation

shuffle:
    resource: '@ShuffleBundle/Controller/'
    type: annotation