# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.message_generator:
        class:      Bundle\AppBundle\Service\MessageGenerator

    app.card_generator:
        class:      Bundle\CardBundle\Service\Card
#        factory:    [Bundle\CardBundle\Service\Card, createCard]
#        arguments:  [value, name, suit, originalDeckPosition]

    app.deck_generator:
        class:      Bundle\DeckBundle\Service\Deck
#        arguments:  ['@app.card_generator']

    app.player:
        class:      Bundle\PlayerBundle\Service\Player
#        arguments:  [name, id]

    app.dealer:
        class:      Bundle\DealerBundle\Service\Dealer

    app.shuffle:
        class:      Bundle\ShuffleBundle\Service\Shuffle
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
